steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ms-wsapi', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ms-wsapi']

  # Deploy to Cloud Run in multiple regions in parallel with unique service names
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        regions=(
          "asia-east1"
          "asia-northeast1"
          "asia-northeast2"
          "europe-north1"
          "europe-southwest1"
          "europe-west1"
          "europe-west4"
          "europe-west8"
          "europe-west9"
          "me-west1"
          "us-central1"
          "us-east1"
          "us-east4"
          "us-east5"
          "us-south1"
          "us-west1"
          "africa-south1"
          "asia-east2"
          "asia-northeast3"
          "asia-southeast1"
          "asia-southeast2"
          "asia-south1"
          "asia-south2"
          "australia-southeast1"
          "australia-southeast2"
          "europe-central2"
          "europe-west10"
          "europe-west12"
          "europe-west2"
          "europe-west3"
          "europe-west6"
          "me-central1"
          "me-central2"
          "northamerica-northeast1"
          "northamerica-northeast2"
          "southamerica-east1"
          "southamerica-west1"
          "us-west2"
          "us-west3"
          "us-west4"
        )
        for region in "${regions[@]}"; do
          (
            gcloud run deploy ms-wsapi \
              --image gcr.io/$PROJECT_ID/ms-wsapi \
              --region $region \
              --platform managed \
              --allow-unauthenticated \
              --port 80 \
              --concurrency 1 \
              --memory 1Gi \
              --cpu 1
          ) &
        done
        wait

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY